<?php

namespace ZMP\AIAssistant;

class Config {

    function __construct( ){

      global $zmpaiassistant;
      global $zmplugin;

      $config = $zmpaiassistant['default_config'];

      /**
      * create ZMPlugin Object from Basename from global var declared in main plugin file
      */
      $zmplugin['zmp-ai-assistant'] = new \ZMP\Plugin\Plugin( $zmpaiassistant['plugin_basename'] );

      /**
      * set an alternative Display Name (MainMenuPage)
      */
      $zmplugin['zmp-ai-assistant']->setDisplayName( $config->pluginname ); //this is autogenerated from slug

      //do a quick version comparison of pluginfile version and config version
      $zmplugin['zmp-ai-assistant']->setConfigVersion( $config->version );
      $zmplugin['zmp-ai-assistant']->checkVersion();


    }


}
